### ISSUE TITLE
sound filenames

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/localizer_auditory_motion#12]
- [x] change the name of the files to be played and how they are organized
- [x] one folder per subject
- [ ] have filed name start at sub-ctrl01 ?
- [x] make `rms` a suffix and not a prefix

**Comment by marcobarilari** [comment]
related to #2

**Comment by marcobarilari** [comment]
see #22 

> have filed name stat at sub-ctrl01 ?

I don't remember what this means, any idea?

**Comment by Remi-Gau** [comment]
hum... I think the idea was "do we NEED to have a 'group' name for each subject?"

Couldn't we just start with "sub-001" then just increase the numbers.

Then if we eventually scan blind participants we can give tham a group prefix.

**Comment by marcobarilari** [comment]
yes, what you say makes sense. I guess it will apply to any data acquired in the first stage of this project for any experiments

**Comment by marcobarilari** [comment]
I think this one can be closed, open it if needed.
